// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talanton.Api.Data;

#nullable disable

namespace Talanton.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827002252_AddLoanApplicationStage")]
    partial class AddLoanApplicationStage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talanton.Api.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SaccoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("SaccoId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicantCooperativeProfile", b =>
                {
                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizedSignatoryName")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizedSignatoryPhone")
                        .HasColumnType("text");

                    b.Property<Guid>("CooperativeId")
                        .HasColumnType("uuid");

                    b.Property<int>("MembershipCount")
                        .HasColumnType("integer");

                    b.HasKey("ApplicantId");

                    b.HasIndex("CooperativeId");

                    b.ToTable("ApplicantCooperativeProfiles");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicantIndividualProfile", b =>
                {
                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("text");

                    b.HasKey("ApplicantId");

                    b.ToTable("ApplicantIndividualProfiles");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedAdministrativeFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ApprovedAnnualSimpleInterestRatePct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ApprovedPrincipal")
                        .HasColumnType("numeric");

                    b.Property<int?>("ApprovedTermMonths")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CommitteeReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<string>("FinalDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeReviewId");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("ApplicationDecisions");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationRequiredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequiredDocumentTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("RequiredDocumentTypeId");

                    b.ToTable("ApplicationRequiredDocuments");
                });

            modelBuilder.Entity("Talanton.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterData")
                        .HasColumnType("text");

                    b.Property<string>("BeforeData")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanVote")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CommitteeReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SaccoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeReviewId");

                    b.HasIndex("SaccoId");

                    b.HasIndex("UserId");

                    b.ToTable("CommitteeMemberships");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuorumRequired")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("CommitteeReviews");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid>("CommitteeReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeReviewId");

                    b.HasIndex("VoterUserId");

                    b.ToTable("CommitteeVotes");
                });

            modelBuilder.Entity("Talanton.Api.Models.Cooperative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SaccoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaccoId");

                    b.ToTable("Cooperatives");
                });

            modelBuilder.Entity("Talanton.Api.Models.CreditAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssessmentVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("NarrativeSummary")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallCreditScore")
                        .HasColumnType("numeric");

                    b.Property<string>("RiskGrade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessedByUserId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("CreditAssessments");
                });

            modelBuilder.Entity("Talanton.Api.Models.CreditKPI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationMethodVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("KpiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KpiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KpiValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditAssessmentId");

                    b.ToTable("CreditKPIs");
                });

            modelBuilder.Entity("Talanton.Api.Models.DocumentVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDocumentId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("DocumentVerifications");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdministrativeFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnnualSimpleInterestRatePct")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ApplicantConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ApplicantConsentReceived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedUnderwriterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUnderwriterUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CounterOfferPrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("CounterOfferReason")
                        .HasColumnType("text");

                    b.Property<string>("CounterOfferStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CounterOfferTermMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SaccoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("AssignedUnderwriterId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SaccoId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("LoanApplicationStatusHistories");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanDisbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdministrativeFeeDeductedAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ApplicationDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisbursementStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NetAmountToBorrower")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentChannel")
                        .HasColumnType("text");

                    b.Property<decimal>("PrincipalDisbursedAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDecisionId");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("ProcessedByUserId");

                    b.ToTable("LoanDisbursements");
                });

            modelBuilder.Entity("Talanton.Api.Models.RequiredDocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedMimeTypes")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCollateralDocumentType")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SaccoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaccoId");

                    b.ToTable("RequiredDocumentTypes");
                });

            modelBuilder.Entity("Talanton.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Talanton.Api.Models.Sacco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Saccos");
                });

            modelBuilder.Entity("Talanton.Api.Models.SaccoMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimaryMember")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SaccoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("SaccoId");

                    b.ToTable("SaccoMemberships");
                });

            modelBuilder.Entity("Talanton.Api.Models.UnderwritingAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreditAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RecommendedAdministrativeFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecommendedAnnualSimpleInterestRatePct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecommendedPrincipal")
                        .HasColumnType("numeric");

                    b.Property<int?>("RecommendedTermMonths")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnderwriterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreditAssessmentId");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("UnderwriterUserId");

                    b.ToTable("UnderwritingAssessments");
                });

            modelBuilder.Entity("Talanton.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("SaccoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaccoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Talanton.Api.Models.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SaccoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SaccoId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("Talanton.Api.Models.Applicant", b =>
                {
                    b.HasOne("Talanton.Api.Models.User", "ApplicantUser")
                        .WithMany()
                        .HasForeignKey("ApplicantUserId");

                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantUser");

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicantCooperativeProfile", b =>
                {
                    b.HasOne("Talanton.Api.Models.Applicant", "Applicant")
                        .WithOne("CooperativeProfile")
                        .HasForeignKey("Talanton.Api.Models.ApplicantCooperativeProfile", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.Cooperative", "Cooperative")
                        .WithMany()
                        .HasForeignKey("CooperativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Cooperative");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicantIndividualProfile", b =>
                {
                    b.HasOne("Talanton.Api.Models.Applicant", "Applicant")
                        .WithOne("IndividualProfile")
                        .HasForeignKey("Talanton.Api.Models.ApplicantIndividualProfile", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationDecision", b =>
                {
                    b.HasOne("Talanton.Api.Models.CommitteeReview", "CommitteeReview")
                        .WithMany()
                        .HasForeignKey("CommitteeReviewId");

                    b.HasOne("Talanton.Api.Models.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeReview");

                    b.Navigation("DecidedByUser");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationDocument", b =>
                {
                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.ApplicationRequiredDocument", b =>
                {
                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.RequiredDocumentType", "RequiredDocumentType")
                        .WithMany()
                        .HasForeignKey("RequiredDocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");

                    b.Navigation("RequiredDocumentType");
                });

            modelBuilder.Entity("Talanton.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Talanton.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeMembership", b =>
                {
                    b.HasOne("Talanton.Api.Models.CommitteeReview", "CommitteeReview")
                        .WithMany()
                        .HasForeignKey("CommitteeReviewId");

                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeReview");

                    b.Navigation("Sacco");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeReview", b =>
                {
                    b.HasOne("Talanton.Api.Models.User", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatedByUser");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Talanton.Api.Models.CommitteeVote", b =>
                {
                    b.HasOne("Talanton.Api.Models.CommitteeReview", "CommitteeReview")
                        .WithMany()
                        .HasForeignKey("CommitteeReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "VoterUser")
                        .WithMany()
                        .HasForeignKey("VoterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeReview");

                    b.Navigation("VoterUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.Cooperative", b =>
                {
                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.CreditAssessment", b =>
                {
                    b.HasOne("Talanton.Api.Models.User", "AssessedByUser")
                        .WithMany()
                        .HasForeignKey("AssessedByUserId");

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessedByUser");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Talanton.Api.Models.CreditKPI", b =>
                {
                    b.HasOne("Talanton.Api.Models.CreditAssessment", "CreditAssessment")
                        .WithMany()
                        .HasForeignKey("CreditAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditAssessment");
                });

            modelBuilder.Entity("Talanton.Api.Models.DocumentVerification", b =>
                {
                    b.HasOne("Talanton.Api.Models.ApplicationDocument", "ApplicationDocument")
                        .WithMany()
                        .HasForeignKey("ApplicationDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId");

                    b.Navigation("ApplicationDocument");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanApplication", b =>
                {
                    b.HasOne("Talanton.Api.Models.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "AssignedUnderwriter")
                        .WithMany()
                        .HasForeignKey("AssignedUnderwriterId");

                    b.HasOne("Talanton.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("AssignedUnderwriter");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanApplicationStatusHistory", b =>
                {
                    b.HasOne("Talanton.Api.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Talanton.Api.Models.LoanDisbursement", b =>
                {
                    b.HasOne("Talanton.Api.Models.ApplicationDecision", "ApplicationDecision")
                        .WithMany()
                        .HasForeignKey("ApplicationDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId");

                    b.Navigation("ApplicationDecision");

                    b.Navigation("LoanApplication");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.RequiredDocumentType", b =>
                {
                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId");

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.SaccoMembership", b =>
                {
                    b.HasOne("Talanton.Api.Models.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.UnderwritingAssessment", b =>
                {
                    b.HasOne("Talanton.Api.Models.CreditAssessment", "CreditAssessment")
                        .WithMany()
                        .HasForeignKey("CreditAssessmentId");

                    b.HasOne("Talanton.Api.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.User", "UnderwriterUser")
                        .WithMany()
                        .HasForeignKey("UnderwriterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditAssessment");

                    b.Navigation("LoanApplication");

                    b.Navigation("UnderwriterUser");
                });

            modelBuilder.Entity("Talanton.Api.Models.User", b =>
                {
                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sacco");
                });

            modelBuilder.Entity("Talanton.Api.Models.UserRoleAssignment", b =>
                {
                    b.HasOne("Talanton.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talanton.Api.Models.Sacco", "Sacco")
                        .WithMany()
                        .HasForeignKey("SaccoId");

                    b.HasOne("Talanton.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Sacco");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Talanton.Api.Models.Applicant", b =>
                {
                    b.Navigation("CooperativeProfile");

                    b.Navigation("IndividualProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
